# Generated by Django 5.1.3 on 2025-10-19 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replacements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='classreplacementrequest',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='replacements.venue'),
        ),
        migrations.CreateModel(
            name='ReplacementBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmarked_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('replacement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='replacements.classreplacementrequest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Replacement Bookmarks',
                'unique_together': {('student', 'replacement')},
            },
        ),
    ]
