# Generated by Django 5.1.3 on 2025-10-22 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replacements', '0002_alter_classreplacementrequest_venue_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venuefeedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'Venue Feedback', 'verbose_name_plural': 'Venue Feedbacks'},
        ),
        migrations.RemoveField(
            model_name='venuefeedback',
            name='rating',
        ),
        migrations.AddField(
            model_name='venuefeedback',
            name='issue_status',
            field=models.CharField(choices=[('moderate', 'Moderate Issue'), ('critical', 'Critical Issue'), ('solved', 'Solved')], default='moderate', max_length=20),
        ),
        migrations.AlterField(
            model_name='venuefeedback',
            name='replacement_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='replacements.classreplacementrequest'),
        ),
    ]
