# Generated by Django 6.0.4 on 2026-05-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replacements', '0006_add_student_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='credit_hours',
            field=models.PositiveSmallIntegerField(default=3, help_text='Credit hours awarded to students.'),
        ),
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Short syllabus or subject description.'),
        ),
        migrations.AddField(
            model_name='subject',
            name='lab_hours_per_week',
            field=models.PositiveSmallIntegerField(default=0, help_text='Lab / practical hours per week.'),
        ),
        migrations.AddField(
            model_name='subject',
            name='lecture_hours_per_week',
            field=models.PositiveSmallIntegerField(default=3, help_text='Lecture contact hours per week.'),
        ),
        migrations.AddField(
            model_name='subject',
            name='total_weeks',
            field=models.PositiveSmallIntegerField(default=14, help_text='Number of teaching weeks in the semester.'),
        ),
        migrations.AddField(
            model_name='subject',
            name='tutorial_hours_per_week',
            field=models.PositiveSmallIntegerField(default=0, help_text='Tutorial / discussion hours per week.'),
        ),
    ]
