# Generated by Django 6.0.4 on 2026-05-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replacements', '0007_subject_hours_and_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='semester',
            name='course',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('LH', 'Landscape & Horticulture'), ('ACC', 'Accounting'), ('BS', 'Business Study')], default='CS', help_text='Course / programme this semester belongs to.', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='course',
            field=models.CharField(blank=True, choices=[('CS', 'Computer Science'), ('LH', 'Landscape & Horticulture'), ('ACC', 'Accounting'), ('BS', 'Business Study')], help_text='Course / department this user belongs to.', max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('name', 'class_name', 'course')},
        ),
    ]
