# Generated by Django 6.0.4 on 2026-05-27 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replacements', '0008_add_course_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday')])),
                ('start_time', models.TimeField(help_text='e.g. 08:00')),
                ('end_time', models.TimeField(help_text='e.g. 10:00')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='replacements.subject')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
    ]
